In [3]:
import numpy as np

s1 = ["a", "b", "a", "a", "c", "a", "b", "c", "b"]
s2 = ["a", "c","b", "a", "c", "b", "b", "a", "c", "a"]


    

opt = np.zeros((len(s1)+1, len(s2)+1))

ref = np.zeros((len(s1)+1, len(s2)+1, 2))
opt

for i in range(1, len(s1)+1):
    for j in range(1, len(s2)+1):
        if s1[i-1] == s2[j-1]:
            opt[i][j]  = opt[i-1][j-1]+1
            ref[i][j][0] = i-1
            ref[i][j][1] = j-1
        else:
            opt[i][j]  =  max(opt[i-1][j],  opt[i][j-1])
            if opt[i-1][j] > opt[i][j-1]:
                ref[i][j][0] = i-1
                ref[i][j][1] = j
            else:
                ref[i][j][0] = i
                ref[i][j][1] = j-1
print(opt)

ref


m = len(s1)
n = len(s2)


while opt[m][n] > 0:
    x,y = int(ref[m][n][0]), int(ref[m][n][1])
    
    if x == m-1 and y == n-1:
        print(s1[m-1])
    m,n = x,y
    #print(m,n)
    

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 1. 2. 3. 3. 3. 3. 3. 3. 3.]
 [0. 1. 1. 2. 3. 3. 3. 3. 4. 4. 4.]
 [0. 1. 2. 2. 3. 4. 4. 4. 4. 5. 5.]
 [0. 1. 2. 2. 3. 4. 4. 4. 5. 5. 6.]
 [0. 1. 2. 3. 3. 4. 5. 5. 5. 5. 6.]
 [0. 1. 2. 3. 3. 4. 5. 5. 5. 6. 6.]
 [0. 1. 2. 3. 3. 4. 5. 6. 6. 6. 6.]]
b
b
c
a
b
a


# Matrix Chain multiplication


In [6]:
import math
dims = [[2,5],[5,8],[8,6],[6,3],[3,4],[4,5]]

opt = np.zeros((len(dims), len(dims)))
ref = np.zeros((len(dims), len(dims)))

#Store cost of multiplying matrix i to j
for length in range(1, len(dims)):
    for start in range(0, len(dims)-length):
        
        
        # find min among every partition
        minCost = math.inf
        minRef = -1
        for partition in range(length):
            cost = opt[start][start + partition]  + opt[start + partition+1][start+length] + dims[start][0]*dims[start + partition][1]*dims[start+length][1]
            if cost < minCost:
                
                minCost = cost
                minRef = start+partition
        opt[start][start+length] = minCost
        ref[start][start+length] = minRef
print(opt)
print(ref)



[[  0.  80. 176. 212. 236. 276.]
 [  0.   0. 240. 264. 324. 399.]
 [  0.   0.   0. 144. 240. 324.]
 [  0.   0.   0.   0.  72. 150.]
 [  0.   0.   0.   0.   0.  60.]
 [  0.   0.   0.   0.   0.   0.]]
[[0. 0. 1. 2. 3. 4.]
 [0. 0. 1. 1. 3. 3.]
 [0. 0. 0. 2. 3. 3.]
 [0. 0. 0. 0. 3. 3.]
 [0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0. 0.]]
